// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AccountEmailAppForm renders the visible "Change Email" view body: a start
// button, a deep-link readout for the one-time email change page, and a status
// line. The document <head> (the composition root's injected theme stylesheet)
// and the ESM module <script> (bundle "account-email" —
// appsassets/dist/account-email.js — resolved through the Renderer's asset
// source) are supplied by Renderer.RenderDoc, so this templ authors only the
// app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp account_email_app.templ:
// the element ids and classes below are the hooks the "account-email" JS
// bundle queries; do not rename them without rebuilding the bundle.
func AccountEmailAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Change Email</h1><p class=\"muted\">Mint a one-time page to change your Pinner email. The change runs in your browser; your password never reaches this chat.</p><button type=\"button\" id=\"em-start\" class=\"btn-primary\">Start email change</button><div class=\"card\"><a id=\"em-url\" href=\"#\" class=\"link-ready\" style=\"display:none\"></a></div><div id=\"em-status\" class=\"status\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
