// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AuthStatusAppForm renders the visible "Account" view body: a status line, an
// authenticated/not-authenticated outcome label, and the account message. The
// refresh is wired by the auth-status ESM bundle. The document <head> (the
// composition root's injected theme stylesheet) and the ESM module <script>
// (bundle "auth-status" — appsassets/dist/auth-status.js — resolved through
// the Renderer's asset source) are supplied by Renderer.RenderDoc, so this
// templ authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp auth_status_app.templ: the
// element ids and classes below are the hooks the "auth-status" JS bundle
// queries; do not rename them without rebuilding the bundle.
func AuthStatusAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Account</h1><div id=\"authstatus-status\" class=\"status\"></div><div class=\"card\"><strong id=\"authstatus-outcome\">—</strong><br><span id=\"authstatus-message\" class=\"muted\"></span></div><button type=\"button\" id=\"authstatus-refresh\" class=\"btn-primary\" disabled>Refresh</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
