// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// IPFSUploadAppForm renders the visible "Upload to IPFS" view body: the file
// picker / name / wait form, the live status line, and the result readout.
// The document <head> (the composition root's injected theme stylesheet) and
// the ESM module <script> (bundle "ipfs-upload" — appsassets/dist/ipfs-upload.js
// — resolved through the Renderer's asset source) are supplied by
// Renderer.RenderDoc, so this templ authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp ipfs_upload_app.templ: the
// element ids and classes below are the hooks the "ipfs-upload" JS bundle
// queries; do not rename them without rebuilding the bundle.
func IPFSUploadAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Upload to IPFS</h1><form id=\"ipfs-upload-form\" class=\"mt-2\"><label for=\"file\" class=\"form-label\">File</label><div class=\"file-field\"><input id=\"file\" name=\"file\" type=\"file\" class=\"file-input\"><div class=\"file-picker\"><span class=\"file-btn\">Choose file</span> <span id=\"file-name\" class=\"file-name\">No file chosen</span></div></div><label for=\"name\" class=\"form-label\">Name (optional)</label> <input id=\"name\" name=\"name\" class=\"form-input\" placeholder=\"my-file\" autocomplete=\"off\"> <button type=\"submit\" class=\"btn-primary\" id=\"start\">Upload</button></form><div id=\"ipfs-upload-status\" class=\"status\"></div><div id=\"ipfs-upload-progress\" class=\"progress hidden\" role=\"progressbar\" aria-valuemin=\"0\" aria-valuemax=\"100\" aria-valuenow=\"0\"><div class=\"progress-track\"><div id=\"ipfs-upload-progress-fill\" class=\"progress-fill\" style=\"width:0%\"></div></div><span id=\"ipfs-upload-progress-label\" class=\"progress-label muted\">—</span></div><div class=\"card\">CID: <code id=\"out-cid\" class=\"mono text-accent\">—</code></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
