// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// IPFSDownloadAppForm renders the visible "Download from IPFS" view body: the
// CID/path + name + output + sink form, the live status line, and the result
// readout (a download link for sink=drop, or the written host path for
// sink=local). The document <head> (the composition root's injected theme
// stylesheet) and the ESM module <script> (bundle "ipfs-download" —
// appsassets/dist/ipfs-download.js — resolved through the Renderer's asset
// source) are supplied by Renderer.RenderDoc, so this templ authors only the
// app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp ipfs_download_app.templ:
// the element ids and classes below are the hooks the "ipfs-download" JS
// bundle queries; do not rename them without rebuilding the bundle.
func IPFSDownloadAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Download from IPFS</h1><form id=\"ipfs-download-form\" class=\"mt-2\"><label for=\"ipfs-source\" class=\"form-label\">CID or CID/path</label> <input id=\"ipfs-source\" name=\"source\" class=\"form-input\" placeholder=\"bafy.../path/to/file\" autocomplete=\"off\"> <label for=\"name\" class=\"form-label\">Name (optional)</label> <input id=\"name\" name=\"name\" class=\"form-input\" placeholder=\"my-file\" autocomplete=\"off\"> <label for=\"output\" class=\"form-label\">Host output path (optional)</label> <input id=\"output\" name=\"output\" class=\"form-input\" placeholder=\"/data/out/report.pdf\" autocomplete=\"off\"><fieldset class=\"mt-2\"><legend class=\"form-label\">Where to write the bytes</legend> <label class=\"inline\"><input id=\"sink-local\" name=\"sink\" type=\"radio\" value=\"local\" checked=\"checked\"> Local host path</label> <label class=\"inline\"><input id=\"sink-drop\" name=\"sink\" type=\"radio\" value=\"drop\"> Filedrop link</label></fieldset><button type=\"submit\" class=\"btn-primary\" id=\"start\">Download</button></form><div id=\"ipfs-download-status\" class=\"status\"></div><div class=\"card\" style=\"display:none\"><a id=\"out-link\" href=\"#\" class=\"text-accent\" download=\"\">Save file</a></div><div class=\"card\" style=\"display:none\">Local path: <code id=\"out-path\" class=\"mono text-accent\">—</code></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
