// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// PinListAppForm renders the visible "Pin list" view body: a status line, a
// count summary, a refresh button, and the pin table. The table rows and the
// refresh are wired by the pin-list ESM bundle. The document <head> (the
// composition root's injected theme stylesheet) and the ESM module <script>
// (bundle "pin-list" — appsassets/dist/pin-list.js — resolved through the
// Renderer's asset source) are supplied by Renderer.RenderDoc, so this templ
// authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp pin_list_app.templ: the
// element ids and classes below are the hooks the "pin-list" JS bundle
// queries; do not rename them without rebuilding the bundle.
func PinListAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Pins</h1><div id=\"pinlist-status\" class=\"status\"></div><div class=\"browser-bar justify-between\"><span id=\"pinlist-count\" class=\"browser-path\"></span> <button type=\"button\" id=\"pinlist-refresh\" class=\"btn-primary !mt-0\" disabled>Refresh</button></div><table class=\"table mt-4\"><thead><tr><th class=\"table-head\">Name</th><th class=\"table-head\">Status</th><th class=\"table-head\">Created</th></tr></thead> <tbody id=\"pinlist-table\"></tbody></table><p id=\"pinlist-empty\" class=\"browser-empty\" hidden></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
