// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// PinCreateAppForm renders the visible "Create a Pin" view body: the CID/name
// form, the live status line, and the result readout. The document <head>
// (the composition root's injected theme stylesheet) and the ESM module
// <script> (bundle "pin" — appsassets/dist/pin.js — resolved through the
// Renderer's asset source) are supplied by Renderer.RenderDoc, so this
// templ authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp pins_app.templ: the
// element ids and classes below are the hooks the "pin" JS bundle queries;
// do not rename them without rebuilding the bundle.
func PinCreateAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Create a Pin</h1><form id=\"pin-form\" class=\"mt-2\"><label for=\"cid\" class=\"form-label\">CID</label> <input id=\"cid\" name=\"cid\" class=\"form-input\" placeholder=\"bafy...\" autocomplete=\"off\" spellcheck=\"false\"> <label for=\"name\" class=\"form-label\">Name (optional)</label> <input id=\"name\" name=\"name\" class=\"form-input\" placeholder=\"my-file\" autocomplete=\"off\"> <button type=\"submit\" class=\"btn-primary\">Pin</button></form><div id=\"pin-status\" class=\"status\"></div><div class=\"card\">CID: <code id=\"out-cid\" class=\"mono text-accent\">—</code><br>Status: <code id=\"out-status\" class=\"mono text-accent\">—</code></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
