// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// VaultCreateAppForm renders the visible "Create Vault" view body: a start
// button, the create URL readout (deep-linked to the human-only one-time page
// where the Sia device approval and seed reveal happen), and a live status
// line that polls the app-only vault_create_status helper until done. The
// document <head> (the composition root's injected theme stylesheet) and the
// ESM module <script> (bundle "vault-create" — appsassets/dist/vault-create.js
// — resolved through the Renderer's asset source) are supplied by
// Renderer.RenderDoc, so this templ authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp vault_create_app.templ:
// the element ids and classes below are the hooks the "vault-create" JS
// bundle queries; do not rename them without rebuilding the bundle.
func VaultCreateAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Create Vault</h1><button id=\"vault-create-start\" type=\"button\" class=\"btn-primary\">Start vault create</button><div class=\"card\">Setup: <a id=\"vault-create-url\" href=\"#\" target=\"_blank\" rel=\"noopener\" class=\"muted underline underline-offset-2\">pending</a></div><div id=\"vault-create-status\" class=\"status\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
