// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// VaultBrowserAppForm renders the visible "Vault browser" view body: a status
// line, the current path label, an up/root/refresh button row, and the listing
// container. Navigation buttons and the listing are wired by the
// "vault-browser" ESM bundle. The document <head> (the composition root's
// injected theme stylesheet) and the ESM module <script> (bundle
// "vault-browser" — appsassets/dist/vault-browser.js — resolved through the
// Renderer's asset source) are supplied by Renderer.RenderDoc, so this templ
// authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp vault_browser_app.templ:
// the element ids and classes below are the hooks the "vault-browser" JS
// bundle queries; do not rename them without rebuilding the bundle.
func VaultBrowserAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Vault</h1><div id=\"vault-status\" class=\"status\"></div><div class=\"browser-bar justify-between\"><span id=\"vault-path\" class=\"browser-path\">vault:/</span><div class=\"flex gap-2\"><button type=\"button\" id=\"vault-up\" class=\"btn-primary !mt-0\" disabled>Up</button> <button type=\"button\" id=\"vault-root\" class=\"btn-primary !mt-0\" disabled>Root</button> <button type=\"button\" id=\"vault-refresh\" class=\"btn-primary !mt-0\" disabled>Refresh</button></div></div><ul id=\"vault-list\" class=\"browser-list\"></ul><p id=\"vault-empty\" class=\"browser-empty\" hidden></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
