// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package canvas

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// VaultRestoreAppForm renders the visible "Restore Vault" view body: a start
// button, the restore URL readout (deep-linked to the human-only one-time page
// where the recovery seed is entered), and a live status line that polls the
// app-only vault_restore_status helper until done. The document <head> (the
// composition root's injected theme stylesheet) and the ESM module <script>
// (bundle "vault-restore" — appsassets/dist/vault-restore.js — resolved
// through the Renderer's asset source) are supplied by Renderer.RenderDoc, so
// this templ authors only the app-specific markup.
//
// Ported unchanged from pinner-cli internal/mcpapp vault_restore_app.templ:
// the element ids and classes below are the hooks the "vault-restore" JS
// bundle queries; do not rename them without rebuilding the bundle.
func VaultRestoreAppForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"app-shell\"><h1 class=\"app-title\">Restore Vault</h1><button id=\"vault-restore-start\" type=\"button\" class=\"btn-primary\">Start vault restore</button><div class=\"card\">Restore: <a id=\"vault-restore-url\" href=\"#\" target=\"_blank\" rel=\"noopener\" class=\"muted underline underline-offset-2\">pending</a></div><div id=\"vault-restore-status\" class=\"status\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
