package canvasassets

import "embed"

// Assets is the embedded source FS for MCP Apps views: the per-app,
// fully-self-contained ESM bundles built by the JS toolchain (pinner-cli's
// packages/apps via tsdown, staged into appsassets/dist/ by `make jsbuild`)
// plus the generated mcpcanvas AssetSource manifest (appsassets/manifest.json).
//
// Each dist/<app>.js bundle is self-contained (zero imports): the whole
// @modelcontextprotocol/ext-apps client (App + PostMessageTransport + MCP SDK +
// zod) plus the app's flow logic are inlined, so a ui:// view can be served as
// a single HTML document with no external dependencies and no runtime module
// loading — the sandboxed iframe cannot resolve file imports.
//
// The mcpcanvas asset-source root is the appsassets subdirectory (it contains
// dist/ and manifest.json); the renderer subs into it.
//
// Assets are gitignored and regenerated by `make assets` before any go build.
//
//go:embed appsassets
var Assets embed.FS

// ThemeCSS is the compiled Tailwind v4 theme for ui:// MCP Apps, built from
// css/input.css by `make cssbuild` (pnpm build:css). It is the single source
// of the app identity: the @theme tokens (dark zinc surface, blue accent,
// status palette) plus the @utility component classes the view bodies
// (authored in go.lumeweb.com/pinner/canvas) and JS bundles reference. The
// output is tree-shaken to exactly the utilities used across apps.
//
// Every app view is served as a single self-contained document to a sandboxed
// iframe, so the stylesheet is inlined (no network request, no runtime JIT);
// the renderer passes it to canvas.NewRenderer as the document theme.
//
// Gitignored; regenerated by `make cssbuild`.
//
//go:embed css/tailwind.css
var ThemeCSS string

// bundleNames maps a view slug to its embedded bundle filename under
// appsassets/dist/. Its key set pins the view inventory the generated manifest
// must cover (manifest_test.go) and that every rendered document selects
// exactly one bundle from (render_test.go). Keys are the canvas.View IDs.
var bundleNames = map[string]string{
	"pin":              "appsassets/dist/pin.js",
	"pin-list":         "appsassets/dist/pin-list.js",
	"vault-browser":    "appsassets/dist/vault-browser.js",
	"vault-create":     "appsassets/dist/vault-create.js",
	"vault-restore":    "appsassets/dist/vault-restore.js",
	"vault-upload":     "appsassets/dist/vault-upload.js",
	"vault-download":   "appsassets/dist/vault-download.js",
	"ipfs-upload":      "appsassets/dist/ipfs-upload.js",
	"ipfs-download":    "appsassets/dist/ipfs-download.js",
	"auth-sso":         "appsassets/dist/auth-sso.js",
	"auth-status":      "appsassets/dist/auth-status.js",
	"account-password": "appsassets/dist/account-password.js",
	"account-email":    "appsassets/dist/account-email.js",
}
