// Package canvasassets is the publishable asset + render seam for ui:// MCP
// Apps, shipped alongside the go.lumeweb.com/pinner/canvas view contracts so
// any composition root can render every canvas.View document by importing
// only go.lumeweb.com/pinner/* — no UI bundle, no stylesheet, and no
// re-implementation of the mcpcanvas.AssetSource contract required.
//
// It carries the embedded source FS (per-app self-contained ESM bundles under
// appsassets/dist/ plus the generated mcpcanvas manifest at
// appsassets/manifest.json) and the compiled Tailwind theme (css/tailwind.css).
// The view bodies and the JS bundles both reference the theme's tokens and
// utilities, so the three version together in this one package.
//
// The epub artifacts are committed and released so a consuming module fetches
// a self-contained canvasassets; they are regenerated by the `make assets`
// pipeline (pnpm apps build + genappmanifest + Tailwind) wired into CI.
//
// Rendering: NewRenderer builds a go.lumeweb.com/pinner/canvas.Renderer over
// the embedded source + theme; Render / RenderVersioned are one-liners that
// render a view's complete document (manifest-verified, version handshake)
// using the canonical title + body for that view. Composition roots that need
// a custom title/body pass the *canvas.Renderer and the view body + version
// per RenderDoc call instead.
package canvasassets
