// Package canvasassets is the importable asset + render seam for ui:// MCP
// Apps in the pinner module. It mirrors the pinner-cli mcpapp surface so a
// hosted composition root (the Portal MCP plugin) can render every
// canvas.View document by importing only go.lumeweb.com/pinner/canvasassets —
// no UI bundle, stylesheet, or re-implementation of the mcpcanvas.AssetSource
// contract required.
//
// It embeds the per-app self-contained ESM bundles (appsassets/dist/*.js) and
// the generated mcpcanvas manifest (appsassets/manifest.json) that the canvas
// delegation resolves every view's bundle through, plus the compiled Tailwind
// theme (css/tailwind.css) inlined into every document.
//
// Assets are gitignored and regenerated by `make assets` (jsbuild + cssbuild +
// genappmanifest) before any go build/test — the same runtime-generation model
// the pinner-cli mcpapp/mcpembed seam used. Consuming modules that fetch pinner
// from the proxy get the source without the generated assets; they regenerate
// them in the module cache before building, exactly as the Portal plugin did
// against pinner-cli/mcpembed.
package canvasassets
