package canvasassets

import (
	"context"
	"io/fs"
	"sync"

	"go.lumeweb.com/mcpcanvas"
	"go.lumeweb.com/pinner/canvas"
)

// canvasRenderer lazily builds the single shared canvas.Renderer exactly once,
// from the embedded asset source (appsassets root: dist bundles +
// appsassets/manifest.json) and the embedded Tailwind theme.
//
// Concurrency: sync.OnceValue guarantees the constructor runs exactly once and
// every caller observes the same *canvas.Renderer; concurrent first callers
// block until initialization completes. The constructor cannot fail on a
// correctly built tree (the embedded manifest is generated by `make assets`),
// so an error is a build/programming error and panics — failing loudly on a
// broken tree instead of serving blank apps. Because OnceValue caches the
// result, a panic is re-raised on every subsequent call rather than retried.
var canvasRenderer = sync.OnceValue(func() *canvas.Renderer {
	root, err := fs.Sub(Assets, "appsassets")
	if err != nil {
		panic("canvasassets: sub appsassets from embedded FS: " + err.Error())
	}
	src, err := mcpcanvas.NewEmbedSource(root)
	if err != nil {
		panic("canvasassets: build mcpcanvas.EmbedSource from appsassets (run `make assets`): " + err.Error())
	}
	r, err := canvas.NewRenderer(src, ThemeCSS)
	if err != nil {
		panic("canvasassets: build canvas renderer: " + err.Error())
	}
	return r
})

// canvasBody maps a canvas view to the go.lumeweb.com/pinner/canvas templ
// body component for that view's screen. The module bodies are pure static
// markup (no parameters), so the mapping is total over AllViews and needs no
// per-view arguments.
func canvasBody(view canvas.View) mcpcanvas.BodyComponent {
	switch view {
	case canvas.ViewPin:
		return canvas.PinCreateAppForm()
	case canvas.ViewPinList:
		return canvas.PinListAppForm()
	case canvas.ViewVaultBrowser:
		return canvas.VaultBrowserAppForm()
	case canvas.ViewVaultCreate:
		return canvas.VaultCreateAppForm()
	case canvas.ViewVaultRestore:
		return canvas.VaultRestoreAppForm()
	case canvas.ViewVaultUpload:
		return canvas.VaultUploadAppForm()
	case canvas.ViewVaultDownload:
		return canvas.VaultDownloadAppForm()
	case canvas.ViewIPFSUpload:
		return canvas.IPFSUploadAppForm()
	case canvas.ViewIPFSDownload:
		return canvas.IPFSDownloadAppForm()
	case canvas.ViewAuthSSO:
		return canvas.AuthSSOAppForm()
	case canvas.ViewAuthStatus:
		return canvas.AuthStatusAppForm()
	case canvas.ViewAccountPassword:
		return canvas.AccountPasswordAppForm()
	case canvas.ViewAccountEmail:
		return canvas.AccountEmailAppForm()
	}
	return nil
}

// RenderAppDoc renders the complete, self-contained ui:// MCP App document for
// view, delegating to the shared canvas.Renderer: the <title>, the inline
// ThemeCSS theme, the view's static templ body from go.lumeweb.com/pinner/canvas,
// and the view's ESM bundle resolved (and sha256-verified) through the
// embedded appsassets manifest, prefixed with the version handshake global.
// The version is the module's default (mcpcanvas normalizes non-semver values
// to "1.0.0").
//
// Unknown views wrap canvas.ErrUnknownView and bundle/manifest problems wrap
// the mcpcanvas sentinels; these are build/programming errors, so they panic
// rather than leak an error into the RenderFunc signature
// (func(canvas.View) string) that appswire.Install consumers use.
func RenderAppDoc(view canvas.View, title string) string {
	body := canvasBody(view)
	if body == nil {
		panic("canvasassets: no canvas body for view " + string(view))
	}
	doc, err := canvasRenderer().RenderDoc(context.Background(), view, title, body, "develop")
	if err != nil {
		panic("canvasassets: render app doc for view " + string(view) + ": " + err.Error())
	}
	return doc
}
