#!/usr/bin/env bash
# Ensure the MCP Apps embed inputs exist for the go.lumeweb.com/pinner module
# the current build resolves against, regenerating them in place when absent.
#
# Why this exists
# ---------------
# pinner's canvasassets package declares `go:embed` over the per-app ESM
# bundles (appsassets/dist/*.js), the mcpcanvas manifest (manifest.json) and
# the compiled Tailwind theme (css/tailwind.css). Those build outputs are
# intentionally NOT git-tracked: pinner owns the JS *source* (packages/apps,
# Makefile) but ships only the source inputs, so the repository stays free of
# committed build artifacts. The outputs are regenerated by `make assets`
# (jsbuild + cssbuild + genappmanifest) from the tracked sources before any
# `go build`/`go test`.
#
# Go's module tooling compiles `go:embed` against the *extracted* copy of a
# dependency — a working-tree checkout under a local `replace`, or the
# read-only module cache under a pinned pseudo-version. Because the embed
# inputs are gitignored, the module-cache copy of canvasassets arrives without
# them, and a consumer that builds pinner from the cache fails with
# "no matching files found".
#
# This script stages the inputs *in place* wherever the current build resolves
# pinner — checkout or module cache — by regenerating them from the tracked JS
# source. It is the single, DRY mechanism shared by every consumer (the CLI,
# the hosted-server/plugin surface, and this module's own test harness): they
# all run it immediately before `go build`/`go test` and get the same embedded
# artifact, with no committed builds and no per-consumer go.mod `replace`.
#
# Pinner's own Makefile runs the same `make assets` pipeline directly (the
# `assets` target) since the module's own build runs from this tree; consumers
# source this script instead.
#
# Design note: we check *existence* (are the artifacts present?), not
# *staleness* (are they up to date?). Detecting staleness from the artifacts
# themselves is unreliable — a stale manifest cannot self-certify its own
# completeness. A `go mod download` bump re-extracts only git-tracked files,
# wiping untracked outputs and tripping the existence check. A developer
# working in a checkout with stale assets already has `make assets` in their
# workflow. Make itself handles incremental rebuilds via mtimes; this script
# does not duplicate that.
#
# Assumption: a single user owns the resolved module dir. Every real consumer
# (CLI, plugin, CI) builds in its own per-user GOMODCACHE (pnpm needs a
# writable cache), so concurrent cross-user builds of the same pinned version
# against one shared read-only cache are not a deployment this script targets.
# It serially locks regeneration for processes under the same user/UID; the
# restore-perms trap covers non-SIGKILL failures; SIGKILL mid-write is left to
# the user's cache hygiene (`go clean -modcache`), same as any truncated cache
# entry.
set -euo pipefail

MODULE="${1:-go.lumeweb.com/pinner}"

# Resolve the directory Go will compile the module from (checkout or cache).
DIR="$(go list -m -f '{{.Dir}}' "$MODULE" 2>/dev/null)"
if [ -z "$DIR" ] || [ ! -d "$DIR" ]; then
    echo "!! ensure-canvasassets: cannot resolve dir for ${MODULE} (go list -m failed)" >&2
    echo "   run 'go mod download' first, or confirm go.mod requires ${MODULE}" >&2
    exit 1
fi

EMBED_DIR="$DIR/canvasassets/appsassets"
EMBED_MANIFEST="$EMBED_DIR/manifest.json"
THEME_CSS="$DIR/canvasassets/css/tailwind.css"
# A stamp written only after a successful `make assets` marks the embed inputs
# as complete. It lives in the gitignored appsassets/ dir, so it is wiped by a
# `go mod download` re-extraction (re-triggering regeneration) and never
# committed. Using a stamp instead of counting/listing bundles avoids both
# false negatives (partial copy) and false positives (stale extra bundles left
# by an app removal in prior builds — jsbuild cp doesn't clean old files).
STAMP="$EMBED_DIR/.assets-stamp"
ASSETS_MAKE_TARGET="${ASSETS_MAKE_TARGET:-assets}"

# Returns 0 (true) when a prior successful `make assets` stamp is absent.
needs_regeneration() {
    [ ! -d "$EMBED_DIR" ] || [ ! -f "$STAMP" ]
}

# Acquire an exclusive lock before checking + regenerating so two concurrent
# invocations sharing the same module-cache dir don't interleave writes. The
# lock is best-effort (flock may be absent on some hosts); when unavailable we
# proceed unprotected rather than fail the build.
# Per-user lock dir avoids a shared /tmp race (a local user could pre-create
# a symlink at a predictable path). Grab the lock before checking+regenerating
# so two concurrent invocations sharing the same module dir don't interleave
# writes. The lock is best-effort (flock may be absent on some hosts).
LOCK_DIR="${XDG_RUNTIME_DIR:-/tmp}/pinner-canvasassets-${UID:-$(id -u)}"
mkdir -p "$LOCK_DIR" 2>/dev/null && chmod 700 "$LOCK_DIR" 2>/dev/null || true
LOCK_FILE="$LOCK_DIR/$(printf '%s' "$DIR" | cksum | awk '{print $1}').lock"
if command -v flock >/dev/null 2>&1; then
    # Lock is best-effort: an unwritable lock dir must not abort the build
    # (set -e), so degrade to unprotected execution on failure.
    exec 9<>"$LOCK_FILE" 2>/dev/null && flock 9 || true
fi

if needs_regeneration; then
    echo ">> ensure-canvasassets: embed inputs missing in $DIR; regenerating."
    if [ ! -f "$DIR/Makefile" ]; then
        echo "!! ensure-canvasassets: $DIR has no Makefile to run 'make $ASSETS_MAKE_TARGET' (pnpm required)" >&2
        exit 1
    fi
    # The module cache is read-only. `make assets` writes to canvasassets/,
    # packages/apps/dist/, and creates node_modules/ at the module root, so we
    # temporarily make the root (for pnpm to create node_modules/) and those
    # subdirs writable, then restore read-only state afterwards.
    #
    # Distinguish "module cache" from "working-tree checkout" by path, not by
    # mode bits: cache dirs are detected directly. This is portable (no GNU
    # `stat -c`) and correct even as root, where [ -w "$DIR" ] is always true
    # and would misclassify a checkout as writable. Only the cache is restored
    # to read-only; a checkout is left untouched.
    cache_dir="$(go env GOMODCACHE 2>/dev/null || true)"
    is_cache=0
    # Guard against an empty GOMODCACHE: with an empty pattern, "$cache_dir"/*
    # would collapse to "*" and match every dir, misclassifying a checkout as
    # cache and stripping its write bits. Only classify when cache_dir is set.
    if [ -n "$cache_dir" ]; then
        case "$DIR" in "$cache_dir"/*) is_cache=1 ;; esac
    fi
    DIRTY_DIRS="canvasassets packages node_modules"
    restore_perms() {
        [ "$is_cache" -eq 1 ] || return 0
        for sub in $DIRTY_DIRS; do
            [ -d "$DIR/$sub" ] && chmod -R -w "$DIR/$sub" 2>/dev/null || true
        done
        chmod -R -w "$DIR" 2>/dev/null || true
    }
    # Restore on EXIT too, so a failure inside make (set -e aborts on it)
    # still returns the read-only cache to its original state.
    trap restore_perms EXIT ERR
    if [ "$is_cache" -eq 1 ]; then
        chmod +w "$DIR" 2>/dev/null || true
        for sub in $DIRTY_DIRS; do
            [ -d "$DIR/$sub" ] && chmod -R +w "$DIR/$sub" 2>/dev/null || true
        done
    fi
    make -C "$DIR" "$ASSETS_MAKE_TARGET"
    touch "$STAMP"
    restore_perms
    trap - EXIT ERR
else
    echo ">> ensure-canvasassets: embed inputs present in $DIR; nothing to do."
fi
